#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing
# Nginx and setting up a 404 page

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
    sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Starting Nginx service
sudo service nginx start

# Allowing Nginx on the firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating a new index with "Hello World!"
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Creating the 404 page
echo -e "Ceci n'est pas une page" > /var/www/html/error_404.html

# Modifying Nginx configuration for the 404 page
sudo sed -i '24i\	location / {' /etc/nginx/sites-available/default
sudo sed -i '25i\		return 404;' /etc/nginx/sites-available/default
sudo sed -i '26i\	}' /etc/nginx/sites-available/default

# Restarting Nginx
sudo service nginx restart

echo -e "\nCompleted.\n"

