#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing Nginx
# Configures Nginx to have a custom 404 page with the string "Ceci n'est pas une page"

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
    sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Starting nginx service
sudo service nginx start

# Allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Configuring 404 page
sudo tee /etc/nginx/sites-available/error_404 <<EOL
server {
    listen 80;
    server_name _;

    location / {
        return 200 'Hello World!';
    }

    location /redirect_me {
        return 301 http://www.example.com;
    }

    location = /error_404.html {
        root /var/www/html;
        internal;
    }

    error_page 404 /error_404.html;

    location /error_404.html {
        internal;
        default_type "text/html";
        return 404 "Ceci n'est pas une page";
    }
}
EOL

sudo ln -s /etc/nginx/sites-available/error_404 /etc/nginx/sites-enabled/
sudo service nginx restart

echo -e "\nCompleted.\n"

