#!/usr/bin/env bash
# Configures Nginx so that its HTTP response contains a custom header(on web-01 and web-2)

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Starting Nginx service
sudo service nginx start

# Allowing Nginx on firewall
sudo ufw allow 'Nginx HTTP'

# User ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create new index with custom header
cat <<EOL > /var/www/html/index.nginx-debian.html
<!DOCTYPE html>
<html>
<head>
    <title>Hello World Page</title>
</head>
<body>
    <h1>Hello World!</h1>
</body>
</html>
EOL

# Add custom HTTP header to Nginx default site configuration
echo -e "server {\n\tlisten 80;\n\tlocation / {\n\t\tadd_header X-Served-By \$host;\n\t\tinclude /etc/nginx/sites-available/default;\n\t}\n}" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restart Nginx
sudo service nginx restart

echo -e "\nCompleted.  \n"

