#!/usr/bin/env bash
# script that configures a server to listening on port 80 of all server's active IPv4 IPs
sudo apt-get update
sudo apt-get install -y net-tools
sudo netstat -tulpn | grep :80
sudo nginx -t
sudo systemctl status nginx
sudo sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
