#!/usr/bin/env bash
# A bash script that create the file /var/run/myscript.pid
#+ Displays To infinity and beyound indefinitely
# Display I hate the kill commmand
# Display Y U no love me?!
# Delete the file /var/run/myscript.pid

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyound"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
