#!/usr/bin/env bash
# loops from 1 - 10 and displays
# "bad luck" at the 4th iteration
# "good luck" at the 8th iteration
# "Best School" at all other iteration

i=1
while [ $i -lt 11 ]
do
  if [ $i -eq 4 ]
  then
    echo "bad luck"
  elif [ $i -eq 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( i++ ))
done
