#!/usr/bin/env bash
# Reload Gunicorn gracefully
if pgrep -x "gunicorn" > /dev/null; then
    echo "Gracefully reloading Gunicorn..."

    # Get the list of process IDs
    pgrep -x "gunicorn" | while read -r pid; do
        # Send signal to gracefully reload Gunicorn
        kill -s HUP "$pid"
    done

    echo "OK"
else
    echo "NOK"
fi

