#!/usr/bin/env bash
# Reload Gunicorn gracefully
if gunicorn_pid=$(pgrep -x "gunicorn")
then
    echo "Gracefully reloading Gunicorn (PID: $gunicorn_pid)..."

    # Send signal to gracefully reload Gunicorn
    if kill -s HUP "$gunicorn_pid"; then
        echo "OK"
    else
        echo "Failed to send signal"
    fi
else
    echo "Gunicorn is not running"
fi

