#!/usr/bin/env bash
# Reload Gunicorn gracefully
if pgrep -x "gunicorn" > /dev/null
then
    echo "Gracefully reloading Gunicorn..."

    # Send signal to gracefully reload Gunicorn
    kill -s HUP "$(pgrep -x "gunicorn")"

    echo "Gunicorn reloaded gracefully."
else
    echo "Gunicorn is not running."
fi

